export const INCREMENT = 'INCREMENT';

export const DELETE_ARTICLE = 'DELETE_ARTICLE';

export const ARTICLE_FILTER_SELECT = 'ARTICLE_FILTER_SELECT';

export const ARTICLE_FILTER_DATE_RANGE = 'ARTICLE_FILTER_DATE_RANGE';
